version: '3.2'

services:

#  jupyter:
#    image: jupyter/all-spark-notebook
#    command: "start-notebook.sh --NotebookApp.token=''"
#    ports:
#      - "18888:8888"
#    volumes:
#      - /data:/home/jovyan/data

  jupyterhub:
    image: ukwa/jupyterhub
    command: "jupyterhub -f /srv/jupyterhub_config/jupyterhub_config.py --no-ssl"
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - "DOCKER_HOST="
      - "DOCKER_NETWORK_NAME=jp_jupyterhub_network"
    # Ensure Hub and Notebook servers are on the same network
    hostname: jupyterhub
    networks:
      - jupyterhub_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/shared:/usr/local/shared/jupyter
      - /data/jupyterhub/jupyterhub_config.py:/srv/jupyterhub_config/jupyterhub_config.py
      - /etc/passwd:/etc/passwd
      - /etc/shadow:/etc/shadow
      - /etc/group:/etc/group
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
   jupyterhub_network:
      driver: overlay

