version: '3.2'

services:

  # PostgreSQL
  postgres:
    image: postgres:9.6.2
    environment:
      - "POSTGRES_USER=w3act"
      - "POSTGRES_PASSWORD=${W3ACT_PSQL_PASSWORD}"
    ports:
      - "5433:5432"
    volumes:
      - "${W3ACT_PSQL_DIR}:/var/lib/postgresql/data"
      - "${W3ACT_DUMPS_DIR}:/var/lib/postresql/dumps"



