version: "3.2"

services:

  hugo:
    image: jojomi/hugo:latest
    volumes:
      - /mnt/gluster/intranet/www/ukwa-reports/:/src
      - /mnt/gluster/intranet/www/html/ukwa-reports/:/output
    environment:
      - HUGO_REFRESH_TIME=3600
      - HUGO_THEME=minimal
      - HUGO_BASEURL=http://intranet.wa.bl.uk/ukwa-reports/
    restart: always

  logviewer:
    image: ukwa/crawl-log-viewer
    ports:
     - "8000:8000"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /mnt/gluster/intranet/www/html/:/usr/share/nginx/html:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf

