
version: '3.2'

services:

  # PostgreSQL for storing task state
  taskdb:
    image: postgres:9.6.2
    environment:
      - "POSTGRES_USER=ingest"
      - "POSTGRES_PASSWORD=ingest"
      - "POSTGRES_DB=ingest_task_state"
    ports:
      - "5432:5432"
    volumes:
      - "/mnt/gluster/ingest/ingest-task-db/postgresql:/var/lib/postgresql/data"
      - "/mnt/gluster/ingest/ingest-task-db/postgresql-in-out-box:/var/lib/postgresql/in-out-box"

  # A UI for poking around in PostgreSQL:
  db-ui:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=wa-sysadm@bl.uk"
      - "PGADMIN_DEFAULT_PASSWORD=ingest"
    ports:
      - 90:80



