version: '3.7'

services:

  spark-master:
    image: bde2020/spark-master:2.4.1-hadoop2.7
    hostname: jupyter.wa.bl.uk
    ports:
      - target: 8180
        published: 8180
        protocol: tcp
        mode: host
      - target: 7077
        published: 7077
        protocol: tcp
        mode: host
#    hostname: spark-master
#    ports:
#      - "8180:8180"
#      - "7077:7077"
#    networks:
#      - default
#      - jupyterhub_network
    environment:
      - "INIT_DAEMON_STEP=setup_spark"
      - "SPARK_MASTER_WEBUI_PORT=8180"
      - "SPARK_MASTER_HOST=jupyter.wa.bl.uk"
#      - "constraint:node==<yourmasternode>"

  spark-worker-1:
    image: bde2020/spark-worker:2.4.1-hadoop2.7
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8181:8181"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8181"
      - "SPARK_PUBLIC_DNS=jupyter.wa.bl.uk"
#      - "constraint:node==<yourworkernode>"
    volumes:
      - /data/shared:/data/shared

#  spark-worker-2:
#    image: bde2020/spark-worker:2.4.1-hadoop2.7
#    container_name: spark-worker-2
#    depends_on:
#      - spark-master
#    ports:
#      - "8081:8081"
#    environment:
#      - "SPARK_MASTER=spark://spark-master:7077"
#      - "constraint:node==<yourworkernode>"  

#networks:
#  jupyterhub_network:
#    external: true
#    name: jupyterhub-network
#
#
# Does not work cross Swarm/not-swarm
#
